from getPlaylistDataFromSpotify import getPlaylistDataFromSpotify
from youtubeLinkScrapper import youtubeLinkScrapper

getPlaylistDataFromSpotify('37i9dQZF1DZ06evO24ABPh')

youtubeLinkScrapper('37i9dQZF1DZ06evO24ABPh')