from getPlaylistDataFromSpotify import getPlaylistDataFromSpotify
from youtubeLinkScrapper import youtubeLinkScrapper

getPlaylistDataFromSpotify('37i9dQZF1DX76Wlfdnj7AP')

youtubeLinkScrazpper('37i9dQZF1DX76Wlfdnj7AP')